---
title: "Lecture 5: Logistics of using C++ in R"
author: "Ciaran Evans"
output: beamer_presentation
---

## Previously

```{r}
Rcpp::cppFunction('double sumC(arma::vec x) {
  int n = x.n_elem;
  double total = 0;
  for(int i = 0; i < n; ++i) {
    total += x[i];
  }
  return total;
}', depends = "RcppArmadillo")

x <- rnorm(10000)
sumC(x)
```

`Rcpp` and `RcppArmadillo` allow us to write functions in R with C++ source code (and the Armadillo library)

## What does this require?

* C++ installed on your computer

* `Rcpp` and `RcppArmadillo` R packages installed

**Challenge:** Getting `Rcpp`, and especially `RcppArmadillo`, to work on your personal computer can very difficult (particularly with Macs)

**Solution:** we are going to use an RStudio Server provided by the DEAC cluster

## Steps

1. Log on to class DEAC OnDemand site: [https://sta379.deac.wfu.edu/](https://sta379.deac.wfu.edu/)

2. Open RStudio app

3. Request resources from DEAC cluster to initialize RStudio session

4. Work in RStudio session through your browser

5. Save work, commit and push to GitHub

6. Quit RStudio session

Full, detailed instructions provided on course website


## Homework 2

* Practice writing functions with C++ source code
* Accept the assignment through GitHub classroom
* Work on RStudio server; clone the GitHub repo in your RStudio server session (see instructions on course website)

