---
title: "Lecture 8: Acceptance-rejection sampling continued"
author: "Ciaran Evans"
output: beamer_presentation
---

## Recap

* Want to sample continuous r.v. $X \sim f$
* Can easily sample from a different density: $Y \sim g$, such that

$$\frac{f(t)}{g(t)} \leq c \hspace{1cm} \text{for all } t \text{ where } f(t) > 0$$

Do the following:

1. Sample $Y \sim g$
2. Sample $U \sim Uniform(0, 1)$
3. If $U \leq \dfrac{f(Y)}{cg(Y)}$, set $X = Y$. Otherwise, return to step 1.

## Illustration

* $Y \sim g$ and $U \sim Uniform(0, 1)$
* *Accept* $Y$ if $U \leq \frac{f(Y)}{cg(Y)}$

:::: {.columns}

::: {.column width="50%"}

```{r, echo=F, message=F, warning=F, fig.width = 4, fig.height=3.5, fig.align='left'}
gridpts <- seq(0, 1, 0.01)
x <- dbeta(gridpts, 2.7, 6.3)
y <- dunif(gridpts)
c = 2.68
plot(gridpts,x,xlim=c(0,1),ylim=c(0,2.8),type="l",col="blue",main="",xlab="",ylab="",
     lwd=1.5)
lines(gridpts,c*y,col="red", lwd=1.5)
#legend(.6,2,c("Target density, f(t)","c * g(t)"),lty=c(1,1),col=c("blue","red"))
```

:::

::: {.column width="50%"}

:::

::::

## Finding $c$

Acceptance-rejection sampling requires that 

$$\frac{f(t)}{g(t)} \leq c \hspace{1cm} \text{for all } t \text{ where } f(t) > 0$$

So, 

$$c = \max_{t:f(t) > 0} \frac{f(t)}{g(t)}$$

## Finding $c$: example

Example from last time:

:::: {.columns}

::: {.column width="60%"}

* $f(t) = \frac{\Gamma(\alpha + \beta)}{\Gamma(\alpha)\Gamma(\beta)} t^{\alpha - 1} (1 - t)^{\beta - 1}$
* $g(t) = 1$ 

:::

::: {.column width="40%"}

$$c = \max_{t:f(t) > 0} \frac{f(t)}{g(t)}$$

:::

::::



\vspace{6cm}



## Why does acceptance-rejection sampling work?

## Your turn

Practice questions on the course website:

[https://sta379-s25.github.io/practice_questions/pq_8.html](https://sta379-s25.github.io/practice_questions/pq_8.html)

* Implement acceptance-rejection sampling for the beta example
* Start in class. You are welcome to work with others
* Practice questions are to help you practice. They are not submitted and not graded
* Solutions are posted on the course website

**Next time:**

* Wrap up: discuss other transformations for generating random variables
* Time to work on HW 3
