---
title: "Challenge 1: The Command Line Murders"
output: 
  rmdformats::robobook:
    css: "homework.css"
    highlight: pygments
link-citations: yes
---

**Overview:** This challenge assignment is a little different! You are going to be solving a text-based murder mystery by learning how to use a Linux-style command line. All you need to do to master this challenge assignment is to email me the solution to the mystery. And since the mystery provides a mechanism for you to check your answer beforehand, no resubmission should be necessary.

**Note:** Remember, challenge assignments must be completed independently. Sharing any hints or solutions to this assignment with any other students is not permitted.

**Due:** Friday, February 7 at 10:00am

## Introduction

The command line is a text-based interface that lets you interact with your computer. You can
use the command line to navigate around your file system, create and edit files, and run programs. A common use for the command line is to interact with version control software like Git, and to connect remotely to computer servers like our very own DEAC cluster.

While not that much in our class *requires* the command line, it is a useful computing tool, and some familiarity with basic commands is essential for high performance computing. The goal of this assignment is to introduce you to some command line basics, through a very cool activity: the Command Line Murders.


## Instructions
1. Read the introduction and instructions for the Command Line Murders:
[https://github.com/veltman/clmystery](https://github.com/veltman/clmystery)
2. Either clone the `clmystery` repository, or download the .zip file to your computer and extract the contents
3. If using Windows, install and set up Cygwin, to mimic a Linux-style command line
([https://www.cygwin.com/](https://www.cygwin.com/))
4. See the Command Line Murders cheat sheet for more details on getting started with the
command line:
[https://github.com/veltman/clmystery/blob/master/cheatsheet.md](https://github.com/veltman/clmystery/blob/master/cheatsheet.md)
5. Open the command line, and navigate to the `clmystery` directory
6. Get started by opening the instructions file (`cat instructions`)
7. When you think you know whodunit, check your solution
[https://github.com/veltman/clmystery/blob/master/solution](https://github.com/veltman/clmystery/blob/master/solution)
8. When you have solved the mystery, send me your solution via email

Good luck, detectives!

